version: '3.8'
services:
  postgres:
    image: postgres
    container_name: my-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /home/adrian-pc/Repo/docker/weight-tracker/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  postgres_data: